################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBZMQ "libzmq")
    if (NOT PC_LIBZMQ_FOUND)
        pkg_check_modules(PC_LIBZMQ "libzmq")
    endif (NOT PC_LIBZMQ_FOUND)
    if (PC_LIBZMQ_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LIBZMQ_CFLAGS} ${PC_LIBZMQ_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBZMQ_INCLUDE_HINTS ${PC_LIBZMQ_INCLUDE_DIRS} ${PC_LIBZMQ_INCLUDE_DIRS}/*)
        set(PC_LIBZMQ_LIBRARY_HINTS ${PC_LIBZMQ_LIBRARY_DIRS} ${PC_LIBZMQ_LIBRARY_DIRS}/*)
    endif(PC_LIBZMQ_FOUND)

find_path (
    LIBZMQ_INCLUDE_DIRS
    NAMES zmq.h
    HINTS ${PC_LIBZMQ_INCLUDE_HINTS}
)

find_library (
    LIBZMQ_LIBRARIES
    NAMES zmq
    HINTS ${PC_LIBZMQ_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBZMQ
    REQUIRED_VARS LIBZMQ_LIBRARIES LIBZMQ_INCLUDE_DIRS
)
mark_as_advanced(
    LIBZMQ_FOUND
    LIBZMQ_LIBRARIES LIBZMQ_INCLUDE_DIRS
)
endif (NOT MSVC)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################


##=============================================================================
#
# CMake - Cross Platform Makefile Generator
# Copyright 2000-2011 Kitware, Inc., Insight Software Consortium
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# * Neither the names of Kitware, Inc., the Insight Software Consortium,
# nor the names of their contributors may be used to endorse or promote
# products derived from this software without specific prior written
# permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  Modified by Jose Luis Rivero <jrivero@osrfoundation.org>
#
##=============================================================================
# - Try to find libzmq headers and libraries
#
# Usage of this module as follows:
#
#     find_package(libzmq)
#
# Variables used by this module, they can change the default behaviour and need
# to be set before calling find_package:
#
#  LIBZMQ_ROOT_DIR  Set this variable to the root installation of
#                            libzmq if the module has problems finding
#                            the proper installation path.
#
# Variables defined by this module:
#
#  LIBZMQ_FOUND              System has LIBZMQ libs/headers
#  LIBZMQ_LIBRARIES          The LIBZMQ libraries
#  LIBZMQ_INCLUDE_DIR        The location of LIBZMQ headers

if(MSVC)
  #add in all the names it can have on windows
  if(CMAKE_GENERATOR_TOOLSET MATCHES "v140" OR MSVC14)
    set(_zmq_TOOLSET "-v140")
  elseif(CMAKE_GENERATOR_TOOLSET MATCHES "v120" OR MSVC12)
    set(_zmq_TOOLSET "-v120")
  elseif(CMAKE_GENERATOR_TOOLSET MATCHES "v110_xp")
    set(_zmq_TOOLSET "-v110_xp")
  elseif(CMAKE_GENERATOR_TOOLSET MATCHES "v110" OR MSVC11)
    set(_zmq_TOOLSET "-v110")
  elseif(CMAKE_GENERATOR_TOOLSET MATCHES "v100" OR MSVC10)
    set(_zmq_TOOLSET "-v100")
  elseif(CMAKE_GENERATOR_TOOLSET MATCHES "v90" OR MSVC90)
    set(_zmq_TOOLSET "-v90")
  endif()

  set(_zmq_versions "4_3_1" "4_3_0" "4_2_5" "4_2_4" "4_2_3" "4_2_2" "4_2_1" "4_2_0")
  set(_zmq_release_names)
  set(_zmq_debug_names)
  foreach( ver ${_zmq_versions})
      list(APPEND _zmq_release_names "libzmq${_zmq_TOOLSET}-mt-s-${ver}")
  endforeach()
  
  foreach( ver ${_zmq_versions})
      list(APPEND _zmq_debug_names "libzmq${_zmq_TOOLSET}-mt-gd-s-${ver}")
  endforeach()

  #now try to find the release and debug version
  find_library(LIBZMQ_LIBRARY_RELEASE
    NAMES ${_zmq_release_names} zmq libzmq
    HINTS ${LIBZMQ_ROOT_DIR}/bin
          ${LIBZMQ_ROOT_DIR}/lib
    )

  find_library(LIBZMQ_LIBRARY_DEBUG
    NAMES ${_zmq_debug_names} zmq libzmq
    HINTS ${LIBZMQ_ROOT_DIR}/bin
          ${LIBZMQ_ROOT_DIR}/lib
    )

  if(LIBZMQ_LIBRARY_RELEASE AND LIBZMQ_LIBRARY_DEBUG)
    set(LIBZMQ_LIBRARY
        debug ${LIBZMQ_LIBRARY_DEBUG}
        optimized ${LIBZMQ_LIBRARY_RELEASE}
        )
  elseif(LIBZMQ_LIBRARY_RELEASE)
    set(LIBZMQ_LIBRARY ${LIBZMQ_LIBRARY_RELEASE})
  elseif(LIBZMQ_LIBRARY_DEBUG)
    set(LIBZMQ_LIBRARY ${LIBZMQ_LIBRARY_DEBUG})
  endif()


  find_path(LIBZMQ_INCLUDE_DIR
    NAMES zmq.h
    HINTS ${LIBZMQ_ROOT_DIR}/include
  )

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(LIBZMQ DEFAULT_MSG
    LIBZMQ_LIBRARY
    LIBZMQ_INCLUDE_DIR
  )

  set(LIBZMQ_INCLUDE_DIRS ${LIBZMQ_INCLUDE_DIR})
  set(LIBZMQ_LIBRARIES ${LIBZMQ_LIBRARY})

  mark_as_advanced(
   LIBZMQ_ROOT_DIR
   LIBZMQ_LIBRARY
   LIBZMQ_LIBRARY_DEBUG
   LIBZMQ_LIBRARY_RELEASE
   LIBZMQ_INCLUDE_DIR
  )

  # LIBZMQ_FOUND is uppercase in Windows, make it compatible with pkgconfig
  if (LIBZMQ_FOUND)
    set(LIBZMQ_FOUND TRUE)
  endif()
endif()